apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: verse
spec:
  type: LoadBalancer
  selector:
    app: coturn
  ports:
    - name: turn-udp
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: turn-tcp
      port: 3478
      targetPort: 3478
      protocol: TCP
    - name: turns-udp
      port: 5349
      targetPort: 5349
      protocol: UDP
    - name: turns-tcp
      port: 5349
      targetPort: 5349
      protocol: TCP
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: coturn-relay
  namespace: verse
spec:
  type: NodePort
  selector:
    app: coturn
  ports:
    - name: relay-udp-50000
      port: 50000
      targetPort: 50000
      protocol: UDP
      nodePort: 31000
    - name: relay-udp-50010
      port: 50010
      targetPort: 50010
      protocol: UDP
      nodePort: 31010
    - name: relay-udp-50020
      port: 50020
      targetPort: 50020
      protocol: UDP
      nodePort: 31020
    - name: relay-udp-50030
      port: 50030
      targetPort: 50030
      protocol: UDP
      nodePort: 31030
    - name: relay-udp-50040
      port: 50040
      targetPort: 50040
      protocol: UDP
      nodePort: 31040
    - name: relay-udp-50050
      port: 50050
      targetPort: 50050
      protocol: UDP
      nodePort: 31050
    - name: relay-udp-50060
      port: 50060
      targetPort: 50060
      protocol: UDP
      nodePort: 31060
    - name: relay-udp-50070
      port: 50070
      targetPort: 50070
      protocol: UDP
      nodePort: 31070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn
  namespace: verse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
    spec:
      containers:
        - name: coturn
          image: docker.io/coturn/coturn:latest
          imagePullPolicy: IfNotPresent
          command: ["turnserver", "-c", "/etc/coturn/turnserver.conf"]
          ports:
            - name: turn-udp
              containerPort: 3478
              protocol: UDP
            - name: turn-tcp
              containerPort: 3478
              protocol: TCP
            - name: turns-udp
              containerPort: 5349
              protocol: UDP
            - name: turns-tcp
              containerPort: 5349
              protocol: TCP
            - name: relay-start
              containerPort: 50000
              protocol: UDP
            - name: relay-end
              containerPort: 50099
              protocol: UDP
          env:
            - name: EXTERNAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: config
              mountPath: /etc/coturn
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: false
            capabilities:
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: config
          configMap:
            name: coturn-config
      restartPolicy: Always
