apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: verse
  labels:
    app: livekit
    component: webrtc
data:
  livekit.yaml: |
    port: 7880
    rtc:
      port_range_start: 50200
      port_range_end: 50299
      use_external_ip: true
      tcp_port: 7881
      # TURN server configuration
      turn_servers:
        - host: coturn
          port: 3478
          protocol: udp
          username: "verse"
          credential: "verse-turn-secret"
    redis:
      address: redis:6379
    keys:
      verse-api-key: verse-api-secret-value-here-change-me
    logging:
      level: info
      sample: false
    room:
      auto_create: true
      empty_timeout: 300
      departure_timeout: 20
    webhook:
      api_key: your-webhook-api-key
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: verse
  labels:
    app: redis
    component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: verse
  labels:
    app: redis
    component: cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
      component: cache
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
        - name: redis
          image: docker.io/redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: verse
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
    component: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: verse
  labels:
    app: livekit
    component: webrtc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: livekit
      component: webrtc
  template:
    metadata:
      labels:
        app: livekit
        component: webrtc
    spec:
      containers:
        - name: livekit
          image: docker.io/livekit/livekit-server:latest
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /etc/livekit/livekit.yaml
            - --node-ip
            - $(POD_IP)
          ports:
            - name: http
              containerPort: 7880
              protocol: TCP
            - name: rtc-tcp
              containerPort: 7881
              protocol: TCP
            - name: turn-udp
              containerPort: 3478
              protocol: UDP
            - name: turn-tls
              containerPort: 5349
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LIVEKIT_PORT
              value: "7880"
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: livekit-secrets
                  key: LIVEKIT_API_KEY
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: livekit-secrets
                  key: LIVEKIT_API_SECRET
          volumeMounts:
            - name: livekit-config
              mountPath: /etc/livekit
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /
              port: 7880
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 7880
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: livekit-config
          configMap:
            name: livekit-config
---
apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: verse
  labels:
    app: livekit
    component: webrtc
spec:
  type: NodePort
  ports:
    - port: 7880
      targetPort: 7880
      protocol: TCP
      name: http
      nodePort: 30880
    - port: 7881
      targetPort: 7881
      protocol: TCP
      name: rtc-tcp
      nodePort: 30881
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: turn-udp
      nodePort: 30478
    - port: 5349
      targetPort: 5349
      protocol: TCP
      name: turn-tls
      nodePort: 30349
  selector:
    app: livekit
    component: webrtc
