apiVersion: apps/v1
kind: Deployment
metadata:
  name: verse-captions
  namespace: verse
  labels:
    app: verse-captions
    component: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verse-captions
      component: ai
  template:
    metadata:
      labels:
        app: verse-captions
        component: ai
    spec:
      containers:
        - name: captions
          image: localhost/verse/captions:latest
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -m
            - apps.captions.main
          args:
            - start
          ports:
            - name: health
              containerPort: 8080
              protocol: TCP
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LIVEKIT_URL
              valueFrom:
                secretKeyRef:
                  name: verse-secrets
                  key: LIVEKIT_URL
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: verse-secrets
                  key: LIVEKIT_API_KEY
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: verse-secrets
                  key: LIVEKIT_API_SECRET
            - name: DEEPGRAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: verse-secrets
                  key: DEEPGRAM_API_KEY
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: verse-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
                  optional: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: verse-captions
  namespace: verse
  labels:
    app: verse-captions
    component: ai
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: health
  selector:
    app: verse-captions
    component: ai
